#!/bin/bash
#SBATCH --job-name=ca_5b_recode_screen
#SBATCH --partition=acpu
#SBATCH --qos=cpu-normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=128G
#SBATCH --time=08:00:00
#SBATCH --array=1-3
#SBATCH --output=/home/mich9173/log/5b_recode_screen_%A_%a.qlog


# Task 1 Decid, 2 Everg, 3 Mixed.

module purge
module load anaconda/2023.09

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate MC0617

export CA_ARCHIVE=/projects/mich9173/CA_carbon
export CA_SCRATCH=/scratch/alpine/mich9173/CA_carbon

Rscript "$HOME/5b_recode_screen.R"
